# TODO verify the names in portuguese
map_areas:

  - slug: bay_of_ice
    type: Sea
    fortification_type:
    barrels_count: 0
    crowns_count: 0
    house_sigil:
    names:
      en: Bay of Ice
      pt: Baía de Gelo

  - slug: sunset_sear
    type: Sea
    fortification_type:
    barrels_count: 0
    crowns_count: 0
    house_sigil:
    names:
      en: Senset Sea
      pt: Mar do Poente

  - slug: ironmans_bay
    type: Sea
    fortification_type:
    barrels_count: 0
    crowns_count: 0
    house_sigil:
    names:
      en: Ironman's Bay
      pt: Baía dos Homens de Ferro

  - slug: golden_sound
    type: Sea
    fortification_type:
    barrels_count: 0
    crowns_count: 0
    house_sigil:
    names:
      en: The Golden Sound
      pt: Canal Dourado

  - slug: west_summer_sea
    type: Sea
    fortification_type:
    barrels_count: 0
    crowns_count: 0
    house_sigil:
    names:
      en: West Summer Sea
      pt: Mar do Verão Oeste

  - slug: redwyne_straights
    type: Sea
    fortification_type:
    barrels_count: 0
    crowns_count: 0
    house_sigil:
    names:
      en: Redwyne Straights
      pt: Estreito de Redwyne

  - slug: east_summer_sea
    type: Sea
    fortification_type:
    barrels_count: 0
    crowns_count: 0
    house_sigil:
    names:
      en: East Summer Sea
      pt: Mar do Verão Leste

  - slug: sea_of_dorne
    type: Sea
    fortification_type:
    barrels_count: 0
    crowns_count: 0
    house_sigil:
    names:
      en: Sea of Dorne
      pt: Mar de Dorne

  - slug: shipbreaker_bay
    type: Sea
    fortification_type:
    barrels_count: 0
    crowns_count: 0
    house_sigil:
    names:
      en: Shipbreaker Bay
      pt: Baía de Quebra de Navios

  - slug: blackwater_bay
    type: Sea
    fortification_type:
    barrels_count: 0
    crowns_count: 0
    house_sigil:
    names:
      en: Blackwater Bay
      pt: Baía da Água Negra

  - slug: narrow_sea
    type: Sea
    fortification_type:
    barrels_count: 0
    crowns_count: 0
    house_sigil:
    names:
      en: The Narrow Sea
      pt: Mar Estreito

  - slug: shivering_sea
    type: Sea
    fortification_type:
    barrels_count: 0
    crowns_count: 0
    house_sigil:
    names:
      en: The Shivering Sea
      pt: Mar do Arrepio

  - slug: castle_black
    type: Land
    fortification_type:
    barrels_count: 0
    crowns_count: 1
    house_sigil:
    names:
      en: Castle Black
      pt: Castelo Negro

  - slug: karhold
    type: Land
    fortification_type:
    barrels_count: 0
    crowns_count: 1
    house_sigil:
    names:
      en: Karhold
      pt: Karhold

  - slug: winterfell
    type: Land
    fortification_type: stronghold
    barrels_count: 1
    crowns_count: 1
    house_sigil: Stark
    names:
      en: Winterfell
      pt: Winterfell

  - slug: port_of_winterfell
    type: Port
    fortification_type:
    barrels_count: 0
    crowns_count: 0
    house_sigil:
    names:
      en: Port of Winterfell
      pt: Porto de Winterfell

  - slug: stony_shore
    type: Land
    fortification_type:
    barrels_count: 1
    crowns_count: 0
    house_sigil:
    names:
      en: The Stony Shore
      pt: Litoral Rochoso

  - slug: white_harbor
    type: Land
    fortification_type: castle
    barrels_count: 0
    crowns_count: 0
    house_sigil:
    names:
      en: White Harbor
      pt: Porto Branco

  - slug: port_of_white_harbor
    type: Port
    fortification_type:
    barrels_count: 0
    crowns_count: 0
    house_sigil:
    names:
      en: Port of White Harbor
      pt: Porto de White Harbor

  - slug: widows_watch
    type: Land
    fortification_type:
    barrels_count: 1
    crowns_count: 0
    house_sigil:
    names:
      en: Whidow's Watch
      pt: Patrulha da Viúva

  - slug: flints_finger
    type: Land
    fortification_type: castle
    barrels_count: 0
    crowns_count: 0
    house_sigil:
    names:
      en: Flint's Finger
      pt: O Dedo de Flint

  - slug: greywater_watch
    type: Land
    fortification_type:
    barrels_count: 1
    crowns_count: 0
    house_sigil:
    names:
      en: Greywater Watch
      pt: Patrulha da Água Cinza

  - slug: moat_cailin
    type: Land
    fortification_type: castle
    barrels_count: 0
    crowns_count: 0
    house_sigil:
    names:
      en: Moat Cailin
      pt: Fosso Cailin

  - slug: seagard
    type: Land
    fortification_type: stronghold
    barrels_count: 1
    crowns_count: 1
    house_sigil:
    names:
      en: Seagard
      pt: Guardamar

  - slug: pyke
    type: Land
    fortification_type: stronghold
    barrels_count: 1
    crowns_count: 1
    house_sigil: Greyjoy
    names:
      en: Pyke
      pt: Pyke

  - slug: port_of_pyke
    type: Port
    fortification_type:
    barrels_count: 0
    crowns_count: 0
    house_sigil:
    names:
      en: Port of Pyke
      pt: Porto de Pyke

  - slug: twins
    type: Land
    fortification_type:
    barrels_count: 0
    crowns_count: 1
    house_sigil:
    names:
      en: The Twins
      pt: As Gêmeas

  - slug: fingers
    type: Land
    fortification_type:
    barrels_count: 1
    crowns_count: 0
    house_sigil:
    names:
      en: The Fingers
      pt: Os Dedos

  - slug: mountains_of_moon
    type: Land
    fortification_type:
    barrels_count: 1
    crowns_count: 0
    house_sigil:
    names:
      en: The Mountains of the Moon
      pt: As Montanhas da Lua

  - slug: eyrie
    type: Land
    fortification_type: castle
    barrels_count: 1
    crowns_count: 1
    house_sigil:
    names:
      en: The Eyrie
      pt: O Ninho da Águia

  - slug: riverrun
    type: Land
    fortification_type: stronghold
    barrels_count: 1
    crowns_count: 1
    house_sigil:
    names:
      en: Riverrun
      pt: Correria

  - slug: lannisport
    type: Land
    fortification_type: stronghold
    barrels_count: 2
    crowns_count: 0
    house_sigil: Lannister
    names:
      en: Lannisport
      pt: Lannisporto

  - slug: port_of_lannisport
    type: Port
    fortification_type:
    barrels_count: 0
    crowns_count: 0
    house_sigil:
    names:
      en: Port of Lannisport
      pt: Porto de Lannisporto

  - slug: harrenhal
    type: Land
    fortification_type: castle
    barrels_count: 0
    crowns_count: 1
    house_sigil:
    names:
      en: Harrenhal
      pt: Harrenhal

  - slug: crackclaw_point
    type: Land
    fortification_type: castle
    barrels_count: 0
    crowns_count: 0
    house_sigil:
    names:
      en: Crackclaw Point
      pt: Ponta da Garra Rachada

  - slug: stoney_sept
    type: Land
    fortification_type:
    barrels_count: 0
    crowns_count: 1
    house_sigil:
    names:
      en: Stoney Sept
      pt: Septo Rochoso

  - slug: dragonstone
    type: Land
    fortification_type: stronghold
    barrels_count: 1
    crowns_count: 1
    house_sigil: Baratheon
    names:
      en: Dragonstone
      pt: Pedra do Dragão

  - slug: port_of_dragonstone
    type: Port
    fortification_type:
    barrels_count: 0
    crowns_count: 0
    house_sigil:
    names:
      en: Port of Dragonstone
      pt: Porto de Pedra do Dragão

  - slug: blackwater
    type: Land
    fortification_type:
    barrels_count: 2
    crowns_count: 0
    house_sigil:
    names:
      en: Blackwater
      pt: Água Negra

  - slug: searoad_marches
    type: Land
    fortification_type:
    barrels_count: 1
    crowns_count: 0
    house_sigil:
    names:
      en: Searoad Marches
      pt: Marchas da Estrada do Mar

  - slug: kings_landing
    type: Land
    fortification_type: stronghold
    barrels_count: 0
    crowns_count: 2
    house_sigil:
    names:
      en: King's Landing
      pt: Porto Real

  - slug: kingswood
    type: Land
    fortification_type:
    barrels_count: 1
    crowns_count: 1
    house_sigil:
    names:
      en: Kingswood
      pt: Mata do Rei

  - slug: reach
    type: Land
    fortification_type: castle
    barrels_count: 0
    crowns_count: 0
    house_sigil:
    names:
      en: The Reach
      pt: Campina

  - slug: highgarden
    type: Land
    fortification_type: stronghold
    barrels_count: 2
    crowns_count: 0
    house_sigil: Tyrell
    names:
      en: Highgarden
      pt: Jardim de Cima

  - slug: oldtown
    type: Land
    fortification_type: stronghold
    barrels_count: 0
    crowns_count: 0
    house_sigil:
    names:
      en: Oldtown
      pt: Vila Velha

  - slug: port_of_oldtown
    type: Port
    fortification_type:
    barrels_count: 0
    crowns_count: 0
    house_sigil:
    names:
      en: Port of Oldtown
      pt: Porto de Vila Velha

  - slug: dornish_marches
    type: Land
    fortification_type:
    barrels_count: 0
    crowns_count: 1
    house_sigil:
    names:
      en: Dornish Marches
      pt: Marchas Dornesas

  - slug: boneway
    type: Land
    fortification_type:
    barrels_count: 0
    crowns_count: 1
    house_sigil:
    names:
      en: The Boneway
      pt: O Caminho de Ossos

  - slug: storms_end
    type: Land
    fortification_type: castle
    barrels_count: 0
    crowns_count: 0
    house_sigil:
    names:
      en: Storms End
      pt: Ponta da Tempestade

  - slug: port_of_storms_end
    type: Port
    fortification_type:
    barrels_count: 0
    crowns_count: 0
    house_sigil:
    names:
      en: Port of Storms End
      pt: Porto de Ponta da Tempestade

  - slug: princes_pass
    type: Land
    fortification_type:
    barrels_count: 1
    crowns_count: 1
    house_sigil:
    names:
      en: Prince's Pass
      pt: Passagem do Príncipe

  - slug: three_towers
    type: Land
    fortification_type:
    barrels_count: 1
    crowns_count: 0
    house_sigil:
    names:
      en: Three Towers
      pt: Três Torres

  - slug: arbor
    type: Land
    fortification_type:
    barrels_count: 0
    crowns_count: 1
    house_sigil:
    names:
      en: The Arbor
      pt: O Arbusto

  - slug: starfall
    type: Land
    fortification_type: castle
    barrels_count: 1
    crowns_count: 0
    house_sigil:
    names:
      en: Starfall
      pt: Queda de Estrela

  - slug: yronwood
    type: Land
    fortification_type: castle
    barrels_count: 0
    crowns_count: 0
    house_sigil:
    names:
      en: Yronwood
      pt: Yronwood

  - slug: salt_shore
    type: Land
    fortification_type:
    barrels_count: 1
    crowns_count: 0
    house_sigil:
    names:
      en: Salt Shore
      pt: Costa de Sal

  - slug: sunspear
    type: Land
    fortification_type: stronghold
    barrels_count: 1
    crowns_count: 1
    house_sigil: Martell
    names:
      en: Sunspear
      pt: Lançasolar

  - slug: port_of_sunspear
    type: Port
    fortification_type:
    barrels_count: 0
    crowns_count: 0
    house_sigil:
    names:
      en: Port of Sunspear
      pt: Porto de Lançasolar
